### ISSUE TITLE
Verify that application works with Win10

### ISSUE THREAD

**Issue by shankera** [MediaComplete/MediaComplete#93]
hahahahahahahhahahaha

**Comment by The9thGod** [comment]
I will be able to verify this tonight.

**Comment by The9thGod** [comment]
Didn't run from the exe, needs further examination as to why / what can fix it.

**Comment by tevert** [comment]
The issue was actually from a hardcoded startup HomeDir of C:\music\library. I've fixed it to be a bit more robust - if the HomeDir is null or does not exist, it falls back on the first AllDirectory that does exist. If that doesn't exist, it falls back on the user's system music directory + "Media Complete".
